### ISSUE TITLE
Session Recording Lab 12 issues

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#104]
- Doc style is not in line with the rest of the labs, numbered sections are missing for example.

- at the third(?) step we get a failure, can;t enable cockpit:
```
[root@sessionrecording ~]# systemctl start cockpit.socket
Failed to start cockpit.socket: Unit cockpit.socket not found.
```
This is because cockpit is not installed on the system and the previous install commands do not drag it in as a dependency

- at the fourth(?) step there are no proper instruction to log into the workstation console to open the browser (see other labs like IdM)

- again at foruth(?) step once we connect to the cockpit service we get a "this connection is not secure" warning. That SHOULD be fixed by providing the workstation with a certificate that is trusted.

- again at fourth(!) step please remind the user what are the root credentials to be used (password: r3dh4t1!)

- Please split in numbered bullet points the actions, hard to refer to individual items otherwise (again see other docs)

PREFERED -> PREFERRED

- remind user to press Save after changing SSSD configureation item

- vim is not installed (although vi is, users that are familiar with it will almost always prefer to use vim)

- OPTIONAL FEEDBACK: I would remove the alternative shell version explanation, it is confusing

"In practise" -> "In practice" (but to be honest I would find a different title)

- password is not provided for user "q" in any place
but then the user "q" doesn't even exist, and no instructions to create it is provided ...

- $ sudo yum install mc nginx
obviously as the user didn;t even exist

- mc is not installed:
```
[q@sessionrecording ~]$ mc
-bash: mc: command not found
```

At this point I stopped trying to complete the lab.

**Comment by sabbaka** [comment]
I am bit confused about no cockpit presence. It is a part of rhel8 base os. I just checked this on latest rhel compose and it's there. I will check this in our summit's VMs.

**Comment by sabbaka** [comment]
I am confirming that for some reason there is no cockpit installed by default on VMs for summit.

**Comment by sabbaka** [comment]
So, about vim should I install it to the VM or should I write about vim installation in the lab? I thought vi is default way for these labs. In other labs vi is being used as well.

**Comment by sabbaka** [comment]
I added text to install vim optionally.

**Comment by sabbaka** [comment]
I think I have addressed and fixed issues described here in https://github.com/RedHatDemos/SecurityDemos/pull/126

**Comment by simo5** [comment]
Now user 'q' already exist, but password is unknown

**Comment by simo5** [comment]
(It's not the one in PR#126)

**Comment by sabbaka** [comment]
This was resolved. We can close the issue.

**Comment by sabbaka** [comment]
@lkerner it's fixed.
