### ISSUE TITLE
Custom Security Content lab1 issues

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#108]
- in the "Hands on" section "before you start" the instructions say:
```
cd /home/lab-user/labs/lab1_introduction/content
```
There is no lab1_introduction directory, there is a lab0_introduction one though

- in "Build the content" section instructions say: "Run make to compile content for all applicable products. A product may be either an OS s.a. RHEL8, RHEL7, Fedora etc"
running make RHEL8, make RHEL7 or make Fedora, each fail because the Makefile targets are lowercase and not uppercase as stated.

- Using shortcuts like ctrl+f should not be suggested because in ravello it is extremely cumbersome to use modifiers like ctrl (I found it can only be done by using the on display keyboard with firefox)

- In "Associated Content" the user is directed to open a directory in nautilus "linux_os/...../accounts_tmout" and then told there is a shared.sh file there.
There is no such file, however there is a shared.sh file in a subdirectory called "bash". The user should be told to look into that subdirectory.

**Comment by simo5** [comment]
Also the guide does not say how to log in the machine (the password should be explicitly stated (r3dh4t1!)

**Comment by matejak** [comment]
The first issue was caused by description/VM discrepancy, which has been fixed on the VM side.
