### ISSUE TITLE
Custom Security Content lab2 issues

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#109]
This lab cannot be done at all, there is no workstation to log into.

**Comment by lkerner** [comment]
Specifically Track 2: Scanning Using OpenSCAP and Scap Workbench. This is a blind copy of the RHEL security lab and must be updated to reflect the Custom Security Lab environment. @dahaic @matejak

**Comment by matejak** [comment]
This is expected, the lab track has been taken from the Lucy's lab, and it not been edited yet.
