### ISSUE TITLE
Lab1 OpenSCAP: unclear instructions

### ISSUE THREAD

**Issue by zpytela** [RedHatDemos/SecurityDemos#112]
This instructions is not clear - Lab 1.1:

>10. Now, go back to your Lab Information webpage from the Lab 0 setup steps and click on the console button for your workstation bastion host. Login as lab-user with r3dh4t1! as the password.

Where can I find the Lab Information webpage?

**Comment by pbeniari** [comment]
Pre-Configured Set Up Steps Section 2.  I recently attended a RHEL 8 overview with the BU and they want customers to continue to use the yum command as opposed to the dnf command.  Their rationale was yum will call dnf but also include enhancements they have built in.  yum is a symbolic link to dnf-3.  Not a big deal, but wanted to pass that along.

**Comment by lkerner** [comment]
went through entire lab exercise and cleaned up wording and made instructions more clear per @zpytela 's suggestion. Also changed dnf to yum to follow RHEL BU advice. FYI: @dahaic and @matejak .
