### ISSUE TITLE
CustomSecurityContent improvements

### ISSUE THREAD

**Issue by ggbecker** [RedHatDemos/SecurityDemos#135]
1 - Custom Security Lab 0 - How to
Suggest to use Paste Text functionality from Ravello to input the password

2 - Introduction Structure suggestions:

Change the way how what is already learned and what has been done for the user is presented (from lab2):

What will you learn -> What you will learn

... what possibilities do you have for remediations of failing rules. -> what are the possibilities for remediations of failing rules.

So the general ideia here is to change the format from question to affirmative, this would have to be applied to the whole lab context.

3 - When firefox is started, it asks if the user wants to restore session which will led you with some tabs from previous exercises and github pages.
  - Clean firefox history
  - Clean bash history

**Comment by ggbecker** [comment]
> 2 - Introduction Structure suggestions:
> 
> Change the way how what is already learned and what has been done for the user is presented (from lab2):
> 
> What will you learn -> What you will learn
> 
> ... what possibilities do you have for remediations of failing rules. -> what are the possibilities for remediations of failing rules.
> 
> So the general ideia here is to change the format from question to affirmative, this would have to be applied to the whole lab context.
> 

This should be addressed by https://github.com/RedHatDemos/SecurityDemos/pull/142/commits/f4786130d3794b09580085c0628588efd4df2595

**Comment by matejak** [comment]
The referenced PR has been merged.
