### ISSUE TITLE
Proposal to make IdM lab smaller

### ISSUE THREAD

**Issue by dahaic** [RedHatDemos/SecurityDemos#143]
As it current stands, IdM lab will take attendee quite a big chunk of the lab time, when 8.4 (groups) is (From the perspective of learning potential) carbon copy of 8.3 (users) and 8.5 has just slight alternations. I was struggling a bit to keep focused during 8.5 :)

My proposal is to *remove* both 8.4 and 8.5 to make lab more approachable. This will enable attendee to check other cool technologies as well.

@simo5 mentioned lack of command line approach to configuration, that could be potential way how to make 8.4 or 8.5 interesting again - not clicking, but using CLI.

What do you think, @pbeniari ?

**Comment by pbeniari** [comment]
I always default to the CLI personally, but for first timers the GUI seems to be easier.  As for eliminating 8.4 and 8.5, rather than eliminate, perhaps we can place a comment in the docs that these sections are for more advanced use cases and are optional.  

What do you guys think? @lkerner @simo5

**Comment by lkerner** [comment]
Agreed @pbeniari . I think we need to make the lab for the most basic user...cause many times windows users even come to our lab at summit... and for those users yes, GUI is easier. I also don't think at this point we eliminate anything... just mark 8.4 and 8.5 as optional as @pbeniari said. Functionally is this IdM lab still working @pbeniari ?

**Comment by lkerner** [comment]
made 8.4 and 8.5 optional
