### ISSUE TITLE
CustomSecurityContent - scan with customized profile

### ISSUE THREAD

**Issue by yuumasato** [RedHatDemos/SecurityDemos#147]
People often ask about scanning with customized profile using oscap.

And a tricky part of it is that the ID of the customized profile is different from original profile.
Should this be considered in the scope of the labs?

If yes, I would suggest to put more emphasis during [customization](https://github.com/RedHatDemos/SecurityDemos/blame/master/2019Labs/CustomSecurityContent/documentation/lab2_openscap.adoc#L185), or add another exercise in which a scan with customized profile is done.

**Comment by yuumasato** [comment]
I cannot assign issues, so ping @matejak and @dahaic.

**Comment by lkerner** [comment]
@matejak @dahaic : as discussed please put this as a note or comment in our lab doc.

**Comment by lkerner** [comment]
@matejak @dahaic : is this issue now resolved?

**Comment by matejak** [comment]
This is not an issue, but an enhancement idea. We went different way for our labs, but if there is a surplus, the OpenSCAP lab exercise can be expanded to be more focused on tailoring.

**Comment by lkerner** [comment]
Ok I will close this since like @matejak says this is not an issue but an enhancement idea.
