### ISSUE TITLE
NBDE Cockpit issues

### ISSUE THREAD

**Issue by dahaic** [RedHatDemos/SecurityDemos#151]
There are three main issues:
1) I was not able to complete it! The "keys" section of encryption tab was not there in my case
2) I believe it's worth having it merged with NBDE lab. (I mean one text, but separate machines, as it is now). First part on `nbde1` node is the same, as well as the introductory text.
2b) If not merged, link needs to be added to the Table of Contents
3) format is a bit off - each step should be numbered

Other points:
* you have to also install `cockpit` package for lab to work
* cockpit https is not trusted
* After clicking on Storage, you have to click on specific drive before you can see Encryption tab (on lab machine, tat's `/dev/vda2`)
* screenshots are off

**Comment by dahaic** [comment]
@sabbaka I cannot assign you, so noticing you this way ^^ :)

**Comment by sabbaka** [comment]
This was resolved. We can close the issue.

**Comment by sabbaka** [comment]
@lkerner it's fixed.
