### ISSUE TITLE
Sizing of the RHEL Security Lab tracks

### ISSUE THREAD

**Issue by dahaic** [RedHatDemos/SecurityDemos#152]
During my dry run, these are the times (focused, but taking notes for feedback, and I am not fast reader, should be fairly average)

OpenSCAP: 18 minutes
SELinux: 50 minutes
NBDE: 7 minutes (not counting waiting for auto unlock)
NBDE Cockpit: 10 minutes but not finished
IPSec: 15 minutes
USB Guard: 15 minutes
Audit: 22 minutes
AIDE: 15 minutes
IdM: I haven't re-run it, my first was, I believe, 60 minutes +
GPG: 7 minutes
FirewallD: 12 minutes
Crypto policies: 8 minutes
Session Recording: 20 minutes, but I got confused by issues :)

**Comment by dahaic** [comment]
@lkerner I believe, if we merge NBDE, we can write somewhere "Labs are usually 15 - 20 minutes, with SELinux and IdM being bigger - about an hour" Or don't use times of individual tracks, and say "All labs are about the same size, except SELinux and IdM being considerably longer to complete. Whole lab is about 4 hours of exercises."

**Comment by lkerner** [comment]
Thanks for the timing breakdown @dahaic ! I think saying in the beginning something like  "All labs are about the same size, except SELinux and IdM being considerably longer to complete. Whole lab is about 4 hours of exercises." is a good idea. I will add this to the intro. Thanks.

**Comment by wrabcak** [comment]
@lkerner  is this fixed?

**Comment by lkerner** [comment]
fixed. added timing to beginning of each lab exercise.
