### ISSUE TITLE
Issues in NBDE, USBGuard, GPG

### ISSUE THREAD

**Issue by dahaic** [RedHatDemos/SecurityDemos#158]
It's mostly nitpicks, but anyway:

NBDE
* sometimes LUKs is used, instead of full capitalization

USBGuard
* 'he/she' can be changed to 'they'
* the preconfiguration notes are a bit unclear, as there is "preliminary knowledge" section. It's still just FYI (you are not supposed to act on that), but it confused me a bit. I was not sure, if I am supposed to create those XML files or not

GPG
* what is referenced as "user ID" is "Real Name" in CLI
* '(O) for Okay' is just fine, instead of 'Okay/Quit'
* "comment" is before OK, so switch those lines

**Comment by dahaic** [comment]
@dkopecek ^^ :)

**Comment by pbeniari** [comment]
I change User ID to Real Name in the GPG doc.  Good catch, thanks.

**Comment by dkopecek** [comment]
@dahaic is this sufficient? https://github.com/RedHatDemos/SecurityDemos/pull/171

**Comment by dahaic** [comment]
Thank you @dkopecek ! Looks good to me.

**Comment by dkopecek** [comment]
> Thank you @dkopecek ! Looks good to me.

Ok, thanks for review!
