### ISSUE TITLE
Nice to haves in Crypto Policies

### ISSUE THREAD

**Issue by dahaic** [RedHatDemos/SecurityDemos#159]
These are not show-stopper, but it made me wonder :)

* 11.1.4 - mention there is message about reboot printed into the terminal, maybe a good point to dive deeper why reboot is not needed this very moment
* is it deliberate to not mention per-package overrides at all? It would be good opportunity to mention it, and warn that it strongly

**Comment by dahaic** [comment]
@simo5 ^^ :)

**Comment by simo5** [comment]
I will try to address the reboot thing, I just avoided it because it is SLOOOOW.
I did not mention package overrides, because this is a lab excercise on using the crypto policies not a documentation guide :-)
