### ISSUE TITLE
OpenSCAP Lab 1.3, step 6 suggest using search

### ISSUE THREAD

**Issue by jwildman** [RedHatDemos/SecurityDemos#195]
What it says.

**Comment by matejak** [comment]
Could you please describe the issue in a sentence? The text you reference reads

> By running either this automatically generated Ansible remediation playbook or bash remediation script, the openscap.example.com machine will be put into compliance to the OSPP security baseline profile.

and it is unclear what does it have to do with search.

**Comment by jwildman** [comment]
As Lucy said, use the search to find the highlighted option rather than
scrolling through the list looking for the rule to change

**Comment by matejak** [comment]
I am sorry, but I don't know what Lucy said. The text I have quoted in my previous comment is step 6 in the [1.3 section](https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/RHELSecurityLab/documentation/lab1_OpenSCAP.adoc#lab-13-automated-security-remediations-with-openscap-and-ansible) of the OpenSCAP exercise in the RHEL Security lab.
That text doesn't relate to finding anything anywhere, and words like `find` or `scroll` are not even present in the exercise. Is it possible that you are referring to some other exercise?

**Comment by lkerner** [comment]
@jwildman , can you clarify?

**Comment by jwildman** [comment]
Sorry for the confusion.  When you bring up the workbench and go to modify the suggeted setting, I believe it says something like "find the entry" or "modify the entry" for some long string.  There is a search funtion in the top right? that can be used.  Lucy pointed this out in class after several of us had spent time scrolling up and down through the entries trying to find the correct one.
