### ISSUE TITLE
lab 5 section 5.6.5

### ISSUE THREAD

**Issue by rhjcd** [RedHatDemos/SecurityDemos#205]
@lkerner 

**problem:**

[lab-user@workstation-3dcb lab5_oval]$ sudo tests/test_suite.py rule --container ssg_test_suite --datastream build/ssg-rhel7-ds.xml accounts_tmout
/usr/bin/env: ‘python2’: No such file or directory

**Should specify python3 in command like this?:**     …lab5_oval]$   sudo python3 tests/test_suite.py rule ….

But I get a password prompt with python3 added to the command :

lab5_oval]$ sudo python3 tests/test_suite.py rule --container ssg_test_suite --datastream build/ssg-rhel7-ds.xml accounts_tmout
Setting console output to log level INFO
INFO - The DataStream contains 2 Benchmarks
INFO - 0 - scap_org.open-scap_cref_ssg-rhel7-xccdf-1.2.xml
INFO - 1 - scap_org.open-scap_cref_ssg-rhel7-pcidss-xccdf-1.2.xml
INFO - Selected Benchmark is 0
INFO - To select a different Benchmark, use --xccdf-id-number option.
INFO - The base image option has been specified, choosing Podman-based test environment.
INFO - Logging into /home/lab-user/labs/lab5_oval/logs/rule-custom-2019-08-04-2132/test_suite.log
**root@10.88.0.2's password:**

**Comment by lkerner** [comment]
@matejak , @dahaic , @yuumasato : please review.

**Comment by matejak** [comment]
This is a bad permission on the root's SSH key, which has to be fixed by a VM redeployment.

**Comment by matejak** [comment]
It should be fixed in the newly deployed VMs, so please check (and see also #207, which fixes the Ansible setup).

**Comment by rhjcd** [comment]
@lkerner @matejak 
Thank you very much for your assistance and attention to this. The issue is resolved.
