### ISSUE TITLE
Labs 1 - 12 Time-To-Completion

### ISSUE THREAD

**Issue by rhjcd** [RedHatDemos/SecurityDemos#208]
@lkerner 

Lab 1: ~10 minutes
Lab 2: ~15 minutes
Lab 3: ~12 minutes
Lab 4: ~8 minutes
Lab 5: ~11-12 minutes
Lab 6: ~10 minutes
Lab 7: ~10 minutes
Lab 8: ~12 minutes
Lab 9: ~11-12 minutes
Lab 10: ~13 minutes
Lab 11: ~14 minutes
Lab 12: ~11 minutes

**Comment by lkerner** [comment]
done. added estimated numerical times to complete each lab in each lab exercise.
