### ISSUE TITLE
suggestion : add icmp lab exercise to RHEL security lab 

### ISSUE THREAD

**Issue by lkerner** [RedHatDemos/SecurityDemos#225]
suggestion to add icmp lab exercise

**Comment by utf-x** [comment]
bump.

**Comment by lkerner** [comment]
@bachradsusi @wrabcak : what do you guys think? do we have time to add this to our 2020 Summit lab? My guess is no due to all the ansible migration work we are doing. Please confirm.

**Comment by wrabcak** [comment]
Confirming we have no time for it.
