### ISSUE TITLE
Screenshot does not match text for HTML guide

### ISSUE THREAD

**Issue by eraser215** [RedHatDemos/SecurityDemos#239]
In the following page:

https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/CustomSecurityContent/documentation/lab1_introduction.adoc

Step 1.2.1 description refers to ssg-rhel8-guide-ospp.html
Step 1.2.1 item v refers to ssg-rhel8-guide-ospp-rhel8.html, and then has a screen shot that does not match.

Suggested Fix: All references should be to ssg-rhel8-guide-ospp-rhel8.html

**Comment by lkerner** [comment]
@matejak @dahaic @yuumasato : can you take a look and fix?

**Comment by matejak** [comment]
Fixed by VM redeployment based on proposal #243
