### ISSUE TITLE
[rfe][suggestion] Modify Workstation machine to have gnome-tweaks installed

### ISSUE THREAD

**Issue by tmichett** [RedHatDemos/SecurityDemos#247]
Modify the workstation VM to have gnome-tweaks installed. Even better, go further and enable some of the maximize/minimize, window list, context menus on the workstation to make it perform more friendly in ravello (easier navigation of gnome3 on RHEL8).

**Comment by lkerner** [comment]
@ggbecker @matejak : can you guys review to see if we should add this to our 2020 Summit custom security lab?

**Comment by tmichett** [comment]
@lkerner -

I've been working on this exact same thing for the GLS training courses. I created a playbook that installs Gnome tweaks and performs the necessary settings to make the WS more friendly.

**Comment by tmichett** [comment]
---
- name: Installation of Gnome-tweaks
  hosts: "{{ variable_host | default('Instructor') }}"

  tasks:
    - name: Install Gnome-Tweaks
      yum:
        name: gnome-tweaks
        state: present

- name: Gnome-Tweaks Settings
  hosts: "{{ variable_host | default('Instructor') }}"
  remote_user: "{{ variable_user | default('kiosk') }}"

  tasks:
    - name: Complete Gnome-Tweaks Settings for Extensions
      command: gsettings set org.gnome.shell enabled-extensions "['apps-menu@gnome-shell-extensions.gcampax.github.com', 'desktop-icons@gnome-shell-extensions.gcampax.github.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'quiet-shortcuts@fourdan.gmail.com', 'window-list@gnome-shell-extensions.gcampax.github.com']"

    - name: Complete Gnome-Tweaks Settings for Windows
      command: gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'

**Comment by tmichett** [comment]
@lkerner -

I just created a new repo and threw the file in there as I figured that would be easiest way to get.

https://github.com/tmichett/AnsiblePlaybooks/blob/master/Gnome/gnome-tweaks.yml
