### ISSUE TITLE
[bug] Fix documentation for lab 4

### ISSUE THREAD

**Issue by tmichett** [RedHatDemos/SecurityDemos#248]
Need to instruct person to switch to the  **lab4_ansible** directory. This needs to be first instruction in 4.2.

**/home/lab-user/labs/lab4_ansible**

[lab-user@workstation-r8338 labs]$ cd lab4_ansible/
[lab-user@workstation-r8338 lab4_ansible]$ 

https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/CustomSecurityContent/documentation/lab4_ansible.adoc

**Comment by lkerner** [comment]
fixed with above commit
