### ISSUE TITLE
Sorry, there are no available GUIDs for lab SECURITYMA3

### ISSUE THREAD

**Issue by Tronde** [RedHatDemos/SecurityDemos#312]
Hi,  
I found a link to this project in [section 7 of the RHEL 7 Security Guide](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/scanning-the-system-for-configuration-compliance-and-vulnerabilities_security-hardening). Trying to setup the lab failed with the message:

> Sorry, there are no available GUIDs for lab SECURITYMA3, please double check that you selected the correct lab code or contact a lab assistant.

Is this why the lab is not public available for everybody or any other reason? I couldn'd find any information about the availabilty whether in the documentation nor in this repo.

Regards,  
Tronde

**Comment by ggbecker** [comment]
The lab environment provided by RedHat is not available publicly. But there is an option to run the same lab using the same instructions on a Fedora virtual machine. The instructions on how to create the Fedora VM you can find in the same repo but in a different file: https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/CustomSecurityContent/documentation/lab0_setup-devconf.adoc#0-4-setting-up-the-lab-environment-using-fedora-virtual-machine

**Comment by Tronde** [comment]
Thanks a lot for pointing that out!
