### ISSUE TITLE
[2020Labs/OpenShiftSecurity] In the lab 3 there is no user specified to be used in the console.

### ISSUE THREAD

**Issue by ptrnull** [RedHatDemos/SecurityDemos#397]
In the lab 2.3 https://github.com/RedHatDemos/SecurityDemos/blob/master/2020Labs/OpenShiftSecurity/documentation/lab3.adoc#environment-walkthrough the text says:
```
Login to OpenShift using the web console and from the Administrator perspective, on the lefthand navigation pane, expand Home and select Projects. If the Developer perspective is shown, select the Developer dropdown and select Administrator. Confirm that the rbac-lab project is displayed in the list of available projects.
```
But the lab is prepared with different users, which one should be used?

**Comment by lkerner** [comment]
@sabre1041 can you take a look and fix accordingly?

**Comment by lkerner** [comment]
Per my gchat, all the lab exercises are executed as cluster-admin. So I don't think there's an issue here. Let us know if we missed somethign @ptrnull
