### ISSUE TITLE
[2020Labs/OpenShiftSecurity] lab5 Lab Exercise Requirements

### ISSUE THREAD

**Issue by ptrnull** [RedHatDemos/SecurityDemos#415]
The "Lab Exercise Requirements" from the lab5 speaks like it is an independent lab and doesn't make any reference to the rest of the training/lab.

**Comment by jgoldsmith613** [comment]
It kind of was built to be completely independent of the rest. How do you think we should tie it in?  Just mention this can be part of a CI/CD pipeline as shown in lab 4, and some other tie ins?

**Comment by ptrnull** [comment]
@jgoldsmith613 I was trying my best with this PR: https://github.com/RedHatDemos/SecurityDemos/pull/417
Do you mind checking it?

**Comment by jgoldsmith613** [comment]
just reviewed.  changes look good to me.
