### ISSUE TITLE
Explain SCAP terminology in more detail in lab1_OpenSCAP.adoc

### ISSUE THREAD

**Issue by dkopecek** [RedHatDemos/SecurityDemos#59]
Some lab users are reported that it would be helpful if we described some of the SCAP terminology in more detail and that it would help them understand more what they are doing. They mentioned specifically a sentence which mentions several cryptic abbreviations: "... PCI-DSS, STIG, C2S, Common, CJIS, and others.". Having these described simply as "content" is too vague for first-time (Open)SCAP users.

**Comment by lkerner** [comment]
OK so we just need to spell out what these acronyms mean @dkopecek ? (So instead of PCI-DSS we say Payment Card Industry Data Security Standard?) @matejak and @dahaic : FYI and thoughts?

**Comment by dkopecek** [comment]
@lkerner I'd say that a short section with a summary / dictionary for each abbreviation would be appreciated by some folks.

**Comment by lkerner** [comment]
has this been fixed @dahaic ?

**Comment by dahaic** [comment]
I have rephrased some parts, and explained abbreviations used at first occurence, in PR #78 @dkopecek can you check the changes, if they are easier to understand now?

**Comment by dkopecek** [comment]
> I have rephrased some parts, and explained abbreviations used at first occurence, in PR #78 @dkopecek can you check the changes, if they are easier to understand now?

LGTM
