### ISSUE TITLE
Lab1 last excercise fails

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#84]
The last item of the last exercise proposes to try/check remediation with ansible, but it fails fue to missing python:

TASK [Gathering Facts] **************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: /usr/bin/python: No such file or directory\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}
	to retry, use: --limit @/root/playbook.retry

**Comment by dahaic** [comment]
Ah right, I forgot about this issue. For posterity, it's due to 'python3' not being available as 'python'. https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html

Can be solved by updating command, or using native rpm.

**Comment by lkerner** [comment]
@dahaic can you solve by the evening of Thurs April 11 when I make the blueprint for the Friday April 12th testing that Eduard organized?
