### ISSUE TITLE
NBDE LAB 3.5

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#92]
After reboot the system does not automatically unlock.
I see no evidence that tang is actually being contacted on NBDE1

**Comment by simo5** [comment]
Ah eventually it did, please add in the instructions that the cryptsetup prompt may be shown for up to X seconds (my guess is more than a minute) and to be patient and wait.

**Comment by lkerner** [comment]
@dkopecek , @sabbaka thoughts?

**Comment by pbeniari** [comment]
I encountered the same issue where the system did not automatically unlock after reboot.

**Comment by dkopecek** [comment]
> @dkopecek , @sabbaka thoughts?

@lkerner, this is fixed, see:

https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/RHELSecurityLab/documentation/lab3_NBDE.adoc#lab-35-reboot-nbde3-and-test-that-nbde-was-successfully-configured

I wrote 2 minutes there as that was my "worst case" experience when testing the lab.

**Comment by simo5** [comment]
Tested Resolved
