### ISSUE TITLE
USBGuard lab issues

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#94]
- Lab 5.1.1
  the demo VM starts but it spews a bounch of errors that USBguard daemon could not be started

- Lab 5.1.2 at step 1, failure:
```
# systemctl enable usbguard --now
Job for usbguard.service failed because the control process exited with error code.
See "systemctl status usbguard.service" and "journalctl -xe" for details.
```
using journalctl-xe will yield broken output due to the VM console, using it |less makes it readbale:
```
Apr 10 13:41:24 localhost.localdomain usbguard-daemon[723]: [1554918084.263] (E) Policy leaks are possible with this permissions!
Apr 10 13:41:24 localhost.localdomain usbguard-daemon[723]: [1554918084.263] (E) Configuration: /etc/usbguard/rules.conf: usbguard::Exception
Apr 10 13:41:24 localhost.localdomain usbguard-daemon[723]: Configuration: /etc/usbguard/rules.conf: usbguard::Exception
Apr 10 13:41:24 localhost.localdomain systemd[1]: usbguard.service: Control process exited, code=exited status=1
```

Could not continue demo.

**Comment by simo5** [comment]
Addendum: PLEASE explain clearly how to disconnect from the virsh console in the instructions. The combination is ctrl+shift+] but it is not obvious and required googling which will not be available in the sumit lab)

**Comment by lkerner** [comment]
@dkopecek tagging you on this issue.

**Comment by dkopecek** [comment]
@simo5 Thanks for testing! I'll have to add a `chmod` step to the doc to have correct permissions on the file.
