### ISSUE TITLE
AIDE Lab issues

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#96]
- Lab 7.4 point 4:
the output of the command in the "termshot" differs from what you get on the actual machine, enough to confuse users.

- Lab 7.4 point 6:
the output of the command in the "termshot" differs from what you get on the actual machine,  the cwd report is /home/student but should be /root

- Lab 7.4 point 10:
reboots are reallly slow, students should be warned to wait

**Comment by mjahoda** [comment]
AIDE is an acronym for Advanced Intrusion Detection Environment (not Audit Intrusion Detection Environmet) as written several times in https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/RHELSecurityLab/documentation/README.adoc

**Comment by pbeniari** [comment]
Will correct as soon as I get access to edit the doc in Github

**Comment by pbeniari** [comment]
Corrected

**Comment by dkopecek** [comment]
> 
>     * Lab 7.4 point 10:
>       reboots are reallly slow, students should be warned to wait

This is fixed, see:

https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/RHELSecurityLab/documentation/lab3_NBDE.adoc#lab-35-reboot-nbde3-and-test-that-nbde-was-successfully-configured

I wrote 2 minutes there as that was my "worst case" experience when testing the lab.

**Comment by dahaic** [comment]
My findings in latest trial:
* servera really looks like a typo, can we rewrite it as "Server A (servera)"? I know it's a nitpick, but it caught my attention
* security guide links to RHEL7 security guide - is that deliberate? Maybe acknowledge AIDE has not changed in the meantime
* 7.3 `vim aide.conf` in every step is not necessary - you already have it open
* "wording 'pressing :wq!' can be confusing for non-vim users used to shortcuts. "Typing" is better word
* In my aide outputs, `.viminfo` has changed (so there is always a finding
* 7.4.4 changing the permission of `/etc/shadow` file should be a separate step

**Comment by pbeniari** [comment]
Changed reference to servera as suggested.  Fixed link to RHEL 7 Security Guide to point directly to the chapter on AIDE.  I left the redundant vim commands alone, just in case they closed the file.  I changed pressing to typing.  .viminfo will change so I can put a reference in to explain that.  I added the step for altering the permissions of /etc/shadow.
