### ISSUE TITLE
IdM lab issues

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#97]
- Lab 8.1 point 2:
The first screenshot does not match actual usage, the current screenshot shows that you need to type "admin" to log in, the actual usage is that a user named "Administrator" is shown and can be clciked upon.

- Lab 8.1 point 3:
It may be worth preparing a desktop link that opens Firefox on the correct idm page right away (better user experience).
Also note that no login (as shown in the doc) is needed, the user is logged in automatically thanks to Kerberos SSO, this should be note d to avoid confusion.

- Lab 8.1 point 11:
ipa-client-install failed on Idm2 but succeeded on Idm3, I suspect firewall issues, but did not investigate further on Idm2.
I used Idm3 instead of Idm2 for the following steps.

- Lab 8.5 point 16:
this point is wrong and makes the exercise fail
The rule need to add a Whom section of "RunAs users" then add an external "root" user as the user to run the comamnd as.
The "RunAs group" part is completely useless and should be removed.

**Comment by pbeniari** [comment]
Agree with 8.5 point 16, not sure why its there.  Out now.  As for 8.1 point 2, admin is the user name for IdM.
