### ISSUE TITLE
Firewalld Lab issues

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#98]
- Firewalld lab mentions iptables in various places (including the schematic image), but apparently RHEL8 is using nftables now..

-Lab 10.4 point 3:
output of --list-services shown differs from the machine. actual output includes cockpit:
```
[root@servera ~]# firewall-cmd --list-services
cockpit dhcpv6-client dns ssh
```
Also last pioint 4 shows no output for --list-services but should show
```
cockpit dhcpv6-client ssh
```
(same for following examples later on)

**Comment by simo5** [comment]
Also the lab doc does not link to the following lab like others do

**Comment by ggbecker** [comment]
Low resolution image:

**Comment by ggbecker** [comment]
>     * Firewalld lab mentions iptables in various places (including the schematic image), but apparently RHEL8 is using nftables now..

iptables is a symlink to xtables-nft-multi
`ls -la /sbin/ | grep tables`
`lrwxrwxrwx.  1 root root      17 Feb  8 11:44 iptables -> xtables-nft-multi`

**Comment by ggbecker** [comment]
firewall-cmd --list-services is returning cockpit in the list as well. The lab doesn't mention this in the results. It seems it is previously configured in the VM. remove it before final snapshot.

**Comment by pbeniari** [comment]
should be good now, just cleaned it up

**Comment by simo5** [comment]
lab still does not link to next one

**Comment by dahaic** [comment]
My nitpicks from latest trial:
* 10.1.4 - a bit confused, I have just done this "start/enable" combo - if it does not work, repetition won't help
* 10.5.3 - `dd` is to remove one line, `dG` all lines till the end of the file
  * when we are removing whole content, what was the point of copying the file in a first place?

**Comment by pbeniari** [comment]
Cleaned up sections 10.1.4 by adding additional explanations.  As fir 10.5.3, we really don't need this section and I have removed it.
