### ISSUE TITLE
cryptopolicies lab issues

### ISSUE THREAD

**Issue by simo5** [RedHatDemos/SecurityDemos#99]
- IP address for crypto2 hosts in /etc/hosts files is broken, and this causes all the lab to fail right away: needs to be changed to 192.168.0.40, that IP is now reserved for crypto2

- httpd service fails to start on boot on crypto2 due to timeouts: add instructions to tell users to start it manually?

**Comment by letoams** [comment]
I tried this lab too, and also do not see the entry in /etc/hosts or DNS, so I cannot find the machine. Also for me it is not 192.168.0.40 so I cannot login via IP address either.

**Comment by simo5** [comment]
This night the new blueprint should fix it, however if you want to try to fix it, simply open the console of 9crypto2 and type ip addr
note down the IP, then go back to crypto.example.com and edit /etc/hosts to fix the IP address of all the test names.

**Comment by simo5** [comment]
Closing as fixed in dev env
